services:
  searxng:
    image: searxng/searxng:latest
    container_name: nomad-searxng
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
      - SEARXNG_SECRET=${SEARXNG_SECRET:-2548799b6b6a31a9c43ad2be65db3ae428466ef57bd79c6d53a7363b6a072ba7}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
